export enum PurchaseAttachmentType {
  PAYMENT_PROOF = "PAYMENT_PROOF",
  INVOICE = "INVOICE",
  RECEIPT = "RECEIPT",
  QUOTATION = "QUOTATION",
  DELIVERY_NOTE = "DELIVERY_NOTE",
  PRODUCT_PHOTO = "PRODUCT_PHOTO",
  SERVICE_EVIDENCE = "SERVICE_EVIDENCE",
  CONTRACT = "CONTRACT",
  OTHER = "OTHER",
}

