export const PRODUCTION_NOTIFICATION_TYPES = {
  PRODUCTION_CREATED: "PRODUCTION_CREATED",
  PRODUCTION_STARTED: "PRODUCTION_STARTED",
  PRODUCTION_COMPLETED: "PRODUCTION_COMPLETED",
  PRODUCTION_START_REQUESTED: "PRODUCTION_START_REQUESTED",
  PRODUCTION_START_APPROVED: "PRODUCTION_START_APPROVED",
  PRODUCTION_START_REJECTED: "PRODUCTION_START_REJECTED",
  PRODUCTION_CLOSE_REQUESTED: "PRODUCTION_CLOSE_REQUESTED",
  PRODUCTION_CLOSE_APPROVED: "PRODUCTION_CLOSE_APPROVED",
  PRODUCTION_CLOSE_REJECTED: "PRODUCTION_CLOSE_REJECTED",
} as const;

export type ProductionNotificationType =
  typeof PRODUCTION_NOTIFICATION_TYPES[keyof typeof PRODUCTION_NOTIFICATION_TYPES];
