type PermissionSeedItem = {
  code: string;
  name: string;
  description: string;
  module: string;
  resource: string;
  action: string;
  type: 'action' | 'page';
};

export const PERMISSIONS_SEED: PermissionSeedItem[] = [
  { code: 'page.dashboard.view', name: 'Ver dashboard', description: 'Acceso a la vista principal', module: 'dashboard', resource: 'dashboard', action: 'view', type: 'page' },
  { code: 'page.profile.view', name: 'Ver perfil', description: 'Acceso a pantalla de perfil', module: 'profile', resource: 'profile', action: 'view', type: 'page' },
  { code: 'page.sessions.view', name: 'Ver sesiones', description: 'Acceso a pantalla de sesiones', module: 'sessions', resource: 'sessions', action: 'view', type: 'page' },
  { code: 'page.users.view', name: 'Ver usuarios', description: 'Acceso a pantalla de usuarios', module: 'users', resource: 'users', action: 'view', type: 'page' },
  { code: 'page.roles.view', name: 'Ver roles', description: 'Acceso a pantalla de roles', module: 'roles', resource: 'roles', action: 'view', type: 'page' },
  { code: 'page.company.view', name: 'Ver empresa', description: 'Acceso a pantalla de empresa', module: 'company', resource: 'company', action: 'view', type: 'page' },
  { code: 'page.catalog.view', name: 'Ver catalogo', description: 'Acceso a pantallas de catalogo', module: 'catalog', resource: 'catalog', action: 'view', type: 'page' },
  { code: 'page.raw-material.view', name: 'Ver materia prima', description: 'Acceso a pantallas de materia prima', module: 'raw_material', resource: 'raw_material', action: 'view', type: 'page' },
  { code: 'page.warehouses.view', name: 'Ver almacenes', description: 'Acceso a pantallas de almacenes', module: 'warehouses', resource: 'warehouses', action: 'view', type: 'page' },
  { code: 'page.providers.view', name: 'Ver proveedores', description: 'Acceso a pantalla de proveedores', module: 'providers', resource: 'providers', action: 'view', type: 'page' },
  { code: 'page.purchases.view', name: 'Ver compras', description: 'Acceso a pantalla de compras', module: 'purchases', resource: 'purchases', action: 'view', type: 'page' },
  { code: 'page.payments.view', name: 'Ver pagos', description: 'Acceso a pantalla de pagos', module: 'payments', resource: 'payments', action: 'view', type: 'page' },
  { code: 'page.production.view', name: 'Ver produccion', description: 'Acceso a pantalla de produccion', module: 'production', resource: 'production', action: 'view', type: 'page' },
  { code: 'page.out-orders.view', name: 'Ver ordenes de salida', description: 'Acceso a pantalla de ordenes de salida', module: 'out_orders', resource: 'out_orders', action: 'view', type: 'page' },
  { code: 'page.security.view', name: 'Ver seguridad', description: 'Acceso a pantalla de seguridad', module: 'security', resource: 'security', action: 'view', type: 'page' },
  { code: 'page.notifications.view', name: 'Ver notificaciones', description: 'Acceso a pantalla de notificaciones', module: 'notifications', resource: 'notifications', action: 'view', type: 'page' },
  { code: 'users.read', name: 'Listar usuarios', description: 'Ver listado de usuarios', module: 'users', resource: 'users', action: 'read', type: 'action' },
  { code: 'users.create', name: 'Crear usuarios', description: 'Crear nuevos usuarios', module: 'users', resource: 'users', action: 'create', type: 'action' },
  { code: 'users.update', name: 'Editar usuarios', description: 'Actualizar perfil de usuarios', module: 'users', resource: 'users', action: 'update', type: 'action' },
  { code: 'users.delete', name: 'Eliminar usuarios', description: 'Desactivar usuarios', module: 'users', resource: 'users', action: 'delete', type: 'action' },
  { code: 'users.restore', name: 'Restaurar usuarios', description: 'Restaurar usuarios desactivados', module: 'users', resource: 'users', action: 'restore', type: 'action' },
  { code: 'users.assign_roles', name: 'Asignar roles', description: 'Cambiar rol de usuarios', module: 'users', resource: 'users', action: 'assign_roles', type: 'action' },
  { code: 'users.assign_permissions', name: 'Asignar permisos', description: 'Asignar permisos directos por usuario', module: 'users', resource: 'users', action: 'assign_permissions', type: 'action' },
  { code: 'users.deny_permissions', name: 'Denegar permisos', description: 'Denegar permisos directos por usuario', module: 'users', resource: 'users', action: 'deny_permissions', type: 'action' },
  { code: 'users.view_effective_permissions', name: 'Ver permisos efectivos', description: 'Consultar permisos efectivos de usuario', module: 'users', resource: 'users', action: 'view_effective_permissions', type: 'action' },
  { code: 'roles.read', name: 'Listar roles', description: 'Ver listado de roles', module: 'roles', resource: 'roles', action: 'read', type: 'action' },
  { code: 'roles.create', name: 'Crear roles', description: 'Crear nuevos roles', module: 'roles', resource: 'roles', action: 'create', type: 'action' },
  { code: 'roles.update', name: 'Editar roles', description: 'Editar roles existentes', module: 'roles', resource: 'roles', action: 'update', type: 'action' },
  { code: 'roles.delete', name: 'Eliminar roles', description: 'Eliminar roles', module: 'roles', resource: 'roles', action: 'delete', type: 'action' },
  { code: 'roles.restore', name: 'Restaurar roles', description: 'Restaurar roles eliminados', module: 'roles', resource: 'roles', action: 'restore', type: 'action' },
  { code: 'roles.assign_permissions', name: 'Asignar permisos a rol', description: 'Asignar permisos base a un rol', module: 'roles', resource: 'roles', action: 'assign_permissions', type: 'action' },
  { code: 'permissions.read', name: 'Listar permisos', description: 'Consultar catalogo de permisos', module: 'permissions', resource: 'permissions', action: 'read', type: 'action' },
  { code: 'purchases.read', name: 'Listar compras', description: 'Ver compras', module: 'purchases', resource: 'purchases', action: 'read', type: 'action' },
  { code: 'purchases.process.request', name: 'Solicitar procesamiento de compra', description: 'Solicitar aprobacion de procesamiento', module: 'purchases', resource: 'purchases', action: 'process.request', type: 'action' },
  { code: 'purchases.approve', name: 'Aprobar compra', description: 'Aprobar procesamiento de compra', module: 'purchases', resource: 'purchases', action: 'approve', type: 'action' },
  { code: 'notifications.read', name: 'Listar notificaciones', description: 'Consultar notificaciones', module: 'notifications', resource: 'notifications', action: 'read', type: 'action' },
  { code: 'notifications.manage', name: 'Gestionar notificaciones', description: 'Marcar, archivar y gestionar notificaciones propias', module: 'notifications', resource: 'notifications', action: 'manage', type: 'action' },
  { code: 'catalog.read', name: 'Consultar catalogo', description: 'Consultar productos, stock, documentos y consultas de catalogo', module: 'catalog', resource: 'catalog', action: 'read', type: 'action' },
  { code: 'catalog.manage', name: 'Gestionar catalogo', description: 'Crear, editar y operar recursos del catalogo', module: 'catalog', resource: 'catalog', action: 'manage', type: 'action' },
  { code: 'catalog.export', name: 'Exportar catalogo', description: 'Exportar reportes del catalogo e inventario', module: 'catalog', resource: 'catalog', action: 'export', type: 'action' },
  { code: 'warehouses.read', name: 'Consultar almacenes', description: 'Consultar almacenes y ubicaciones', module: 'warehouses', resource: 'warehouses', action: 'read', type: 'action' },
  { code: 'warehouses.manage', name: 'Gestionar almacenes', description: 'Crear, editar y activar almacenes/ubicaciones', module: 'warehouses', resource: 'warehouses', action: 'manage', type: 'action' },
  { code: 'suppliers.read', name: 'Consultar proveedores', description: 'Consultar proveedores y codigos de proveedor por SKU', module: 'suppliers', resource: 'suppliers', action: 'read', type: 'action' },
  { code: 'suppliers.manage', name: 'Gestionar proveedores', description: 'Crear, editar y activar proveedores y codigos por SKU', module: 'suppliers', resource: 'suppliers', action: 'manage', type: 'action' },
  { code: 'payments.read', name: 'Consultar pagos', description: 'Consultar pagos y cuotas de credito', module: 'payments', resource: 'payments', action: 'read', type: 'action' },
  { code: 'payments.manage', name: 'Gestionar pagos', description: 'Crear y eliminar pagos y cuotas de credito', module: 'payments', resource: 'payments', action: 'manage', type: 'action' },
  { code: 'payment-methods.read', name: 'Consultar metodos de pago', description: 'Consultar metodos de pago y asignaciones', module: 'payment_methods', resource: 'payment_methods', action: 'read', type: 'action' },
  { code: 'payment-methods.manage', name: 'Gestionar metodos de pago', description: 'Crear, editar, activar y eliminar metodos de pago y asignaciones', module: 'payment_methods', resource: 'payment_methods', action: 'manage', type: 'action' },
  { code: 'production.read', name: 'Listar produccion', description: 'Consultar ordenes de produccion', module: 'production', resource: 'production', action: 'read', type: 'action' },
  { code: 'production.create', name: 'Crear orden de produccion', description: 'Crear nuevas ordenes de produccion', module: 'production', resource: 'production', action: 'create', type: 'action' },
  { code: 'production.update', name: 'Editar orden de produccion', description: 'Actualizar datos de orden de produccion', module: 'production', resource: 'production', action: 'update', type: 'action' },
  { code: 'production.start', name: 'Iniciar orden de produccion', description: 'Iniciar una orden de produccion', module: 'production', resource: 'production', action: 'start', type: 'action' },
  { code: 'production.close', name: 'Cerrar orden de produccion', description: 'Cerrar una orden de produccion', module: 'production', resource: 'production', action: 'close', type: 'action' },
  { code: 'production.cancel', name: 'Cancelar orden de produccion', description: 'Cancelar una orden de produccion', module: 'production', resource: 'production', action: 'cancel', type: 'action' },
  { code: 'production.extra-time', name: 'Agregar tiempo extra', description: 'Agregar tiempo extra a una orden de produccion', module: 'production', resource: 'production', action: 'extra-time', type: 'action' },
  { code: 'production.image.upload', name: 'Subir imagen de produccion', description: 'Subir evidencia fotografica de produccion', module: 'production', resource: 'production', action: 'image.upload', type: 'action' },
  { code: 'production.export', name: 'Exportar produccion', description: 'Exportar reportes de produccion', module: 'production', resource: 'production', action: 'export', type: 'action' },
  { code: 'security.read', name: 'Consultar seguridad', description: 'Consultar metricas y reportes de seguridad', module: 'security', resource: 'security', action: 'read', type: 'action' },
  { code: 'security.export', name: 'Exportar auditoria de seguridad', description: 'Exportar auditoria de seguridad a CSV', module: 'security', resource: 'security', action: 'export', type: 'action' },
  { code: 'security.blacklist.manage', name: 'Gestionar blacklist de seguridad', description: 'Agregar o remover IPs en blacklist manual', module: 'security', resource: 'blacklist', action: 'manage', type: 'action' },
];

export const ROLE_PERMISSION_SEED: Record<string, string[]> = {
  admin: ['*'],
  moderator: [
    'page.dashboard.view',
    'page.profile.view',
    'page.sessions.view',
    'page.users.view',
    'page.purchases.view',
    'page.catalog.view',
    'page.raw-material.view',
    'catalog.read',
    'catalog.manage',
    'catalog.export',
    'warehouses.read',
    'warehouses.manage',
    'suppliers.read',
    'suppliers.manage',
    'payments.read',
    'payments.manage',
    'payment-methods.read',
    'payment-methods.manage',
    'page.warehouses.view',
    'page.providers.view',
    'page.payments.view',
    'page.production.view',
    'page.out-orders.view',
    'page.notifications.view',
    'production.read',
    'production.create',
    'production.update',
    'production.start',
    'production.close',
    'production.cancel',
    'production.extra-time',
    'production.image.upload',
    'production.export',
    'users.read',
    'users.create',
    'users.update',
    'users.delete',
    'users.restore',
    'users.assign_roles',
    'users.view_effective_permissions',
    'roles.read',
    'purchases.read',
    'purchases.process.request',
    'notifications.read',
    'notifications.manage',
  ],
  adviser: [
    'page.dashboard.view',
    'page.profile.view',
    'page.sessions.view',
    'page.purchases.view',
    'catalog.read',
    'warehouses.read',
    'suppliers.read',
    'payments.read',
    'payment-methods.read',
    'page.catalog.view',
    'page.raw-material.view',
    'page.warehouses.view',
    'page.providers.view',
    'page.payments.view',
    'page.notifications.view',
    'purchases.read',
    'purchases.process.request',
    'notifications.read',
    'notifications.manage',
  ],
};

