type PermissionSeedItem = {
  code: string;
  name: string;
  description: string;
  module: string;
  resource: string;
  action: string;
  type: 'action' | 'page';
};

const CATALOG_FINE_PAGE_PERMISSIONS: PermissionSeedItem[] = [
  { code: 'page.products.view', name: 'Ver productos', description: 'Acceso a pantalla de productos terminados', module: 'catalog', resource: 'products', action: 'view', type: 'page' },
  { code: 'page.materials.view', name: 'Ver materia prima', description: 'Acceso a pantalla de materia prima', module: 'raw_material', resource: 'materials', action: 'view', type: 'page' },
  { code: 'page.product-transfers.view', name: 'Ver transferencias de productos', description: 'Acceso a transferencias de productos terminados', module: 'catalog', resource: 'product_transfers', action: 'view', type: 'page' },
  { code: 'page.material-transfers.view', name: 'Ver transferencias de materia prima', description: 'Acceso a transferencias de materia prima', module: 'raw_material', resource: 'material_transfers', action: 'view', type: 'page' },
  { code: 'page.product-adjustments.view', name: 'Ver ajustes de productos', description: 'Acceso a ajustes de productos terminados', module: 'catalog', resource: 'product_adjustments', action: 'view', type: 'page' },
  { code: 'page.material-adjustments.view', name: 'Ver ajustes de materia prima', description: 'Acceso a ajustes de materia prima', module: 'raw_material', resource: 'material_adjustments', action: 'view', type: 'page' },
  { code: 'page.product-movements.view', name: 'Ver movimientos de productos', description: 'Acceso a kardex de productos terminados', module: 'catalog', resource: 'product_movements', action: 'view', type: 'page' },
  { code: 'page.material-movements.view', name: 'Ver movimientos de materia prima', description: 'Acceso a kardex de materia prima', module: 'raw_material', resource: 'material_movements', action: 'view', type: 'page' },
  { code: 'page.product-inventory.view', name: 'Ver inventario de productos', description: 'Acceso a inventario de productos terminados', module: 'catalog', resource: 'product_inventory', action: 'view', type: 'page' },
  { code: 'page.material-inventory.view', name: 'Ver inventario de materia prima', description: 'Acceso a inventario de materia prima', module: 'raw_material', resource: 'material_inventory', action: 'view', type: 'page' },
];

const CATALOG_FINE_ACTION_PERMISSIONS: PermissionSeedItem[] = [
  { code: 'products.view', name: 'Listar productos', description: 'Consultar listado de productos terminados', module: 'catalog', resource: 'products', action: 'view', type: 'action' },
  { code: 'products.view_detail', name: 'Ver detalle de producto', description: 'Consultar detalle, SKUs, recetas y equivalencias de productos', module: 'catalog', resource: 'products', action: 'view_detail', type: 'action' },
  { code: 'products.create', name: 'Crear productos', description: 'Crear productos terminados', module: 'catalog', resource: 'products', action: 'create', type: 'action' },
  { code: 'products.update', name: 'Editar productos', description: 'Editar productos terminados', module: 'catalog', resource: 'products', action: 'update', type: 'action' },
  { code: 'products.delete', name: 'Desactivar productos', description: 'Desactivar productos terminados', module: 'catalog', resource: 'products', action: 'delete', type: 'action' },
  { code: 'products.restore', name: 'Restaurar productos', description: 'Restaurar productos terminados', module: 'catalog', resource: 'products', action: 'restore', type: 'action' },
  { code: 'products.export', name: 'Exportar productos', description: 'Exportar productos terminados a Excel', module: 'catalog', resource: 'products', action: 'export', type: 'action' },
  { code: 'products.recipes.manage', name: 'Gestionar recetas de producto', description: 'Crear y editar recetas de productos terminados', module: 'catalog', resource: 'products_recipes', action: 'manage', type: 'action' },
  { code: 'products.equivalences.manage', name: 'Gestionar equivalencias de producto', description: 'Crear y eliminar equivalencias de productos terminados', module: 'catalog', resource: 'products_equivalences', action: 'manage', type: 'action' },
  { code: 'materials.view', name: 'Listar materia prima', description: 'Consultar listado de materia prima', module: 'raw_material', resource: 'materials', action: 'view', type: 'action' },
  { code: 'materials.view_detail', name: 'Ver detalle de materia prima', description: 'Consultar detalle, SKUs y equivalencias de materia prima', module: 'raw_material', resource: 'materials', action: 'view_detail', type: 'action' },
  { code: 'materials.create', name: 'Crear materia prima', description: 'Crear materia prima', module: 'raw_material', resource: 'materials', action: 'create', type: 'action' },
  { code: 'materials.update', name: 'Editar materia prima', description: 'Editar materia prima', module: 'raw_material', resource: 'materials', action: 'update', type: 'action' },
  { code: 'materials.delete', name: 'Desactivar materia prima', description: 'Desactivar materia prima', module: 'raw_material', resource: 'materials', action: 'delete', type: 'action' },
  { code: 'materials.restore', name: 'Restaurar materia prima', description: 'Restaurar materia prima', module: 'raw_material', resource: 'materials', action: 'restore', type: 'action' },
  { code: 'materials.export', name: 'Exportar materia prima', description: 'Exportar materia prima a Excel', module: 'raw_material', resource: 'materials', action: 'export', type: 'action' },
  { code: 'materials.equivalences.manage', name: 'Gestionar equivalencias de materia prima', description: 'Crear y eliminar equivalencias de materia prima', module: 'raw_material', resource: 'materials_equivalences', action: 'manage', type: 'action' },
  { code: 'packs.view', name: 'Listar packs', description: 'Consultar listado de packs', module: 'packs', resource: 'packs', action: 'view', type: 'action' },
  { code: 'packs.view_detail', name: 'Ver detalle de pack', description: 'Consultar detalle de pack', module: 'packs', resource: 'packs', action: 'view_detail', type: 'action' },
  { code: 'packs.create', name: 'Crear packs', description: 'Crear packs', module: 'packs', resource: 'packs', action: 'create', type: 'action' },
  { code: 'packs.update', name: 'Editar packs', description: 'Editar packs', module: 'packs', resource: 'packs', action: 'update', type: 'action' },
  { code: 'packs.delete', name: 'Desactivar packs', description: 'Desactivar packs', module: 'packs', resource: 'packs', action: 'delete', type: 'action' },
  { code: 'packs.restore', name: 'Restaurar packs', description: 'Restaurar packs', module: 'packs', resource: 'packs', action: 'restore', type: 'action' },
  { code: 'packs.export', name: 'Exportar packs', description: 'Exportar packs a Excel', module: 'packs', resource: 'packs', action: 'export', type: 'action' },
  { code: 'inventory.products.view', name: 'Ver inventario de productos', description: 'Consultar inventario de productos terminados', module: 'catalog', resource: 'inventory_products', action: 'view', type: 'action' },
  { code: 'inventory.materials.view', name: 'Ver inventario de materia prima', description: 'Consultar inventario de materia prima', module: 'raw_material', resource: 'inventory_materials', action: 'view', type: 'action' },
  { code: 'inventory.products.export', name: 'Exportar inventario de productos', description: 'Exportar inventario de productos terminados', module: 'catalog', resource: 'inventory_products', action: 'export', type: 'action' },
  { code: 'inventory.materials.export', name: 'Exportar inventario de materia prima', description: 'Exportar inventario de materia prima', module: 'raw_material', resource: 'inventory_materials', action: 'export', type: 'action' },
  { code: 'inventory.forecast.view', name: 'Ver forecast de inventario', description: 'Ver proyeccion de stock por SKU', module: 'catalog', resource: 'inventory_forecast', action: 'view', type: 'action' },
  { code: 'inventory.realtime.view', name: 'Ver inventario realtime', description: 'Recibir stream realtime de inventario', module: 'catalog', resource: 'inventory_realtime', action: 'view', type: 'action' },
  { code: 'inventory-ledger.products.view', name: 'Ver movimientos de productos', description: 'Consultar movimientos de productos terminados', module: 'catalog', resource: 'inventory_ledger_products', action: 'view', type: 'action' },
  { code: 'inventory-ledger.materials.view', name: 'Ver movimientos de materia prima', description: 'Consultar movimientos de materia prima', module: 'raw_material', resource: 'inventory_ledger_materials', action: 'view', type: 'action' },
  { code: 'inventory-ledger.products.export', name: 'Exportar movimientos de productos', description: 'Exportar movimientos de productos terminados', module: 'catalog', resource: 'inventory_ledger_products', action: 'export', type: 'action' },
  { code: 'inventory-ledger.materials.export', name: 'Exportar movimientos de materia prima', description: 'Exportar movimientos de materia prima', module: 'raw_material', resource: 'inventory_ledger_materials', action: 'export', type: 'action' },
  { code: 'transfers.products.view', name: 'Ver transferencias de productos', description: 'Consultar transferencias de productos terminados', module: 'catalog', resource: 'transfers_products', action: 'view', type: 'action' },
  { code: 'transfers.products.create', name: 'Crear transferencias de productos', description: 'Crear transferencias de productos terminados en borrador', module: 'catalog', resource: 'transfers_products', action: 'create', type: 'action' },
  { code: 'transfers.products.process', name: 'Procesar transferencias de productos', description: 'Procesar transferencias de productos terminados', module: 'catalog', resource: 'transfers_products', action: 'process', type: 'action' },
  { code: 'transfers.products.cancel', name: 'Cancelar transferencias de productos', description: 'Cancelar transferencias de productos terminados', module: 'catalog', resource: 'transfers_products', action: 'cancel', type: 'action' },
  { code: 'transfers.products.export', name: 'Exportar transferencias de productos', description: 'Exportar transferencias de productos terminados', module: 'catalog', resource: 'transfers_products', action: 'export', type: 'action' },
  { code: 'transfers.materials.view', name: 'Ver transferencias de materia prima', description: 'Consultar transferencias de materia prima', module: 'raw_material', resource: 'transfers_materials', action: 'view', type: 'action' },
  { code: 'transfers.materials.create', name: 'Crear transferencias de materia prima', description: 'Crear transferencias de materia prima en borrador', module: 'raw_material', resource: 'transfers_materials', action: 'create', type: 'action' },
  { code: 'transfers.materials.process', name: 'Procesar transferencias de materia prima', description: 'Procesar transferencias de materia prima', module: 'raw_material', resource: 'transfers_materials', action: 'process', type: 'action' },
  { code: 'transfers.materials.cancel', name: 'Cancelar transferencias de materia prima', description: 'Cancelar transferencias de materia prima', module: 'raw_material', resource: 'transfers_materials', action: 'cancel', type: 'action' },
  { code: 'transfers.materials.export', name: 'Exportar transferencias de materia prima', description: 'Exportar transferencias de materia prima', module: 'raw_material', resource: 'transfers_materials', action: 'export', type: 'action' },
  { code: 'adjustments.products.view', name: 'Ver ajustes de productos', description: 'Consultar ajustes de productos terminados', module: 'catalog', resource: 'adjustments_products', action: 'view', type: 'action' },
  { code: 'adjustments.products.create', name: 'Crear ajustes de productos', description: 'Crear ajustes de productos terminados en borrador', module: 'catalog', resource: 'adjustments_products', action: 'create', type: 'action' },
  { code: 'adjustments.products.process', name: 'Procesar ajustes de productos', description: 'Procesar ajustes de productos terminados', module: 'catalog', resource: 'adjustments_products', action: 'process', type: 'action' },
  { code: 'adjustments.products.cancel', name: 'Cancelar ajustes de productos', description: 'Cancelar ajustes de productos terminados', module: 'catalog', resource: 'adjustments_products', action: 'cancel', type: 'action' },
  { code: 'adjustments.products.export', name: 'Exportar ajustes de productos', description: 'Exportar ajustes de productos terminados', module: 'catalog', resource: 'adjustments_products', action: 'export', type: 'action' },
  { code: 'adjustments.materials.view', name: 'Ver ajustes de materia prima', description: 'Consultar ajustes de materia prima', module: 'raw_material', resource: 'adjustments_materials', action: 'view', type: 'action' },
  { code: 'adjustments.materials.create', name: 'Crear ajustes de materia prima', description: 'Crear ajustes de materia prima en borrador', module: 'raw_material', resource: 'adjustments_materials', action: 'create', type: 'action' },
  { code: 'adjustments.materials.process', name: 'Procesar ajustes de materia prima', description: 'Procesar ajustes de materia prima', module: 'raw_material', resource: 'adjustments_materials', action: 'process', type: 'action' },
  { code: 'adjustments.materials.cancel', name: 'Cancelar ajustes de materia prima', description: 'Cancelar ajustes de materia prima', module: 'raw_material', resource: 'adjustments_materials', action: 'cancel', type: 'action' },
  { code: 'adjustments.materials.export', name: 'Exportar ajustes de materia prima', description: 'Exportar ajustes de materia prima', module: 'raw_material', resource: 'adjustments_materials', action: 'export', type: 'action' },
  { code: 'inventory-alerts.view', name: 'Ver alertas de inventario', description: 'Consultar alertas inteligentes de inventario', module: 'catalog', resource: 'inventory_alerts', action: 'view', type: 'action' },
  { code: 'inventory-alerts.configure', name: 'Configurar alertas de inventario', description: 'Configurar umbrales de alertas inteligentes de inventario', module: 'catalog', resource: 'inventory_alerts', action: 'configure', type: 'action' },
  { code: 'inventory-alerts.receive_toast', name: 'Recibir alertas visuales de inventario', description: 'Recibir notificaciones visuales de inventario inteligente', module: 'catalog', resource: 'inventory_alerts', action: 'receive_toast', type: 'action' },
  { code: 'inventory-alerts.receive_mail', name: 'Recibir alertas por correo de inventario', description: 'Recibir notificaciones persistentes o correo de inventario inteligente', module: 'catalog', resource: 'inventory_alerts', action: 'receive_mail', type: 'action' },
  { code: 'inventory-alerts.acknowledge', name: 'Marcar alerta de inventario revisada', description: 'Marcar alertas inteligentes de inventario como revisadas', module: 'catalog', resource: 'inventory_alerts', action: 'acknowledge', type: 'action' },
  { code: 'inventory-alerts.resolve', name: 'Resolver alerta de inventario', description: 'Resolver alertas inteligentes de inventario', module: 'catalog', resource: 'inventory_alerts', action: 'resolve', type: 'action' },
  { code: 'inventory-alerts.run', name: 'Ejecutar evaluacion de inventario', description: 'Ejecutar evaluacion manual de inventario inteligente', module: 'catalog', resource: 'inventory_alerts', action: 'run', type: 'action' },
];

const PRODUCTION_FINE_ACTION_PERMISSIONS: PermissionSeedItem[] = [
  { code: 'production.view_detail', name: 'Ver detalle de produccion', description: 'Ver detalle completo de una orden de produccion', module: 'production', resource: 'production', action: 'view_detail', type: 'action' },
  { code: 'production.view_all', name: 'Ver toda la produccion', description: 'Permite ver todas las ordenes de produccion del sistema', module: 'production', resource: 'production', action: 'view_all', type: 'action' },
  { code: 'production.view_created_by_others', name: 'Ver produccion de otros usuarios', description: 'Permite ver ordenes de produccion creadas por otros usuarios', module: 'production', resource: 'production', action: 'view_created_by_others', type: 'action' },
  { code: 'production.view_creator_info', name: 'Ver creador de produccion', description: 'Permite ver que usuario creo una orden de produccion', module: 'production', resource: 'production', action: 'view_creator_info', type: 'action' },
  { code: 'production.edit_draft', name: 'Editar borradores de produccion', description: 'Editar ordenes de produccion en estado borrador', module: 'production', resource: 'production', action: 'edit_draft', type: 'action' },
  { code: 'production.edit_processed', name: 'Editar produccion procesada', description: 'Editar campos controlados de ordenes de produccion ya iniciadas o completadas', module: 'production', resource: 'production', action: 'edit_processed', type: 'action' },
  { code: 'production.start.request', name: 'Solicitar inicio de produccion', description: 'Solicitar aprobacion para iniciar una orden de produccion', module: 'production', resource: 'production', action: 'start.request', type: 'action' },
  { code: 'production.approve_start', name: 'Aprobar inicio de produccion', description: 'Aprobar o rechazar solicitudes de inicio de produccion', module: 'production', resource: 'production', action: 'approve_start', type: 'action' },
  { code: 'production.close.request', name: 'Solicitar cierre de produccion', description: 'Solicitar aprobacion para cerrar e ingresar produccion a almacen', module: 'production', resource: 'production', action: 'close.request', type: 'action' },
  { code: 'production.approve_close', name: 'Aprobar cierre de produccion', description: 'Aprobar o rechazar solicitudes de cierre de produccion', module: 'production', resource: 'production', action: 'approve_close', type: 'action' },
  { code: 'production.cancel_draft', name: 'Cancelar borradores de produccion', description: 'Cancelar ordenes de produccion en estado borrador', module: 'production', resource: 'production', action: 'cancel_draft', type: 'action' },
  { code: 'production.cancel_in_progress', name: 'Cancelar produccion en proceso', description: 'Cancelar ordenes de produccion en proceso o parciales', module: 'production', resource: 'production', action: 'cancel_in_progress', type: 'action' },
  { code: 'production.delete_completed', name: 'Revertir produccion completada', description: 'Eliminar o revertir ordenes de produccion completadas', module: 'production', resource: 'production', action: 'delete_completed', type: 'action' },
  { code: 'production.image.upload_extra', name: 'Subir imagen adicional de produccion', description: 'Subir evidencias fotograficas adicionales de produccion', module: 'production', resource: 'production', action: 'image.upload_extra', type: 'action' },
  { code: 'production.view_history', name: 'Ver historial de produccion', description: 'Ver historial y auditoria de ordenes de produccion', module: 'production', resource: 'production', action: 'view_history', type: 'action' },
  { code: 'production.receive_created_notifications', name: 'Recibir notificaciones de produccion creada', description: 'Recibir notificaciones cuando se crean ordenes de produccion', module: 'production', resource: 'production', action: 'receive_created_notifications', type: 'action' },
  { code: 'production.receive_started_notifications', name: 'Recibir notificaciones de produccion iniciada', description: 'Recibir notificaciones cuando se inician ordenes de produccion', module: 'production', resource: 'production', action: 'receive_started_notifications', type: 'action' },
  { code: 'production.receive_completed_notifications', name: 'Recibir notificaciones de produccion completada', description: 'Recibir notificaciones cuando se completan ordenes de produccion', module: 'production', resource: 'production', action: 'receive_completed_notifications', type: 'action' },
  { code: 'production.receive_approval_notifications', name: 'Recibir solicitudes de aprobacion de produccion', description: 'Recibir notificaciones de solicitudes de aprobacion de produccion', module: 'production', resource: 'production', action: 'receive_approval_notifications', type: 'action' },
];

export const PERMISSIONS_SEED: PermissionSeedItem[] = [
  { code: 'page.dashboard.view', name: 'Ver dashboard', description: 'Acceso a la vista principal', module: 'dashboard', resource: 'dashboard', action: 'view', type: 'page' },
  { code: 'page.users.view', name: 'Ver usuarios', description: 'Acceso a pantalla de usuarios', module: 'users', resource: 'users', action: 'view', type: 'page' },
  { code: 'page.roles.view', name: 'Ver roles', description: 'Acceso a pantalla de roles', module: 'roles', resource: 'roles', action: 'view', type: 'page' },
  { code: 'page.company.view', name: 'Ver empresa', description: 'Acceso a pantalla de empresa', module: 'company', resource: 'company', action: 'view', type: 'page' },
  { code: 'page.catalog.view', name: 'Ver catalogo', description: 'Acceso a pantallas de catalogo', module: 'catalog', resource: 'catalog', action: 'view', type: 'page' },
  { code: 'page.products.view', name: 'Ver productos', description: 'Acceso a la pantalla de productos', module: 'catalog', resource: 'products', action: 'view', type: 'page' },
  { code: 'page.product-transfers.view', name: 'Ver transferencias de productos', description: 'Acceso a transferencias de productos', module: 'catalog', resource: 'product_transfers', action: 'view', type: 'page' },
  { code: 'page.product-adjustments.view', name: 'Ver ajustes de productos', description: 'Acceso a ajustes de productos', module: 'catalog', resource: 'product_adjustments', action: 'view', type: 'page' },
  { code: 'page.product-inventory.view', name: 'Ver inventario de productos', description: 'Acceso al inventario de productos', module: 'catalog', resource: 'product_inventory', action: 'view', type: 'page' },
  { code: 'page.product-movements.view', name: 'Ver kardex de productos', description: 'Acceso a movimientos de productos', module: 'catalog', resource: 'product_movements', action: 'view', type: 'page' },
  { code: 'page.materials.view', name: 'Ver materiales', description: 'Acceso a la pantalla de materiales', module: 'raw_material', resource: 'materials', action: 'view', type: 'page' },
  { code: 'page.material-inventory.view', name: 'Ver inventario de materiales', description: 'Acceso al inventario de materiales', module: 'raw_material', resource: 'material_inventory', action: 'view', type: 'page' },
  { code: 'page.material-adjustments.view', name: 'Ver ajustes de materiales', description: 'Acceso a ajustes de materiales', module: 'raw_material', resource: 'material_adjustments', action: 'view', type: 'page' },
  { code: 'page.material-transfers.view', name: 'Ver transferencias de materiales', description: 'Acceso a transferencias de materiales', module: 'raw_material', resource: 'material_transfers', action: 'view', type: 'page' },
  { code: 'page.material-movements.view', name: 'Ver kardex de materiales', description: 'Acceso a movimientos de materiales', module: 'raw_material', resource: 'material_movements', action: 'view', type: 'page' },
  { code: 'page.raw-material.view', name: 'Ver materia prima', description: 'Acceso a pantallas de materia prima', module: 'raw_material', resource: 'raw_material', action: 'view', type: 'page' },
  { code: 'page.warehouses.view', name: 'Ver almacenes', description: 'Acceso a pantallas de almacenes', module: 'warehouses', resource: 'warehouses', action: 'view', type: 'page' },
  { code: 'page.clients.view', name: 'Ver clientes', description: 'Acceso a pantalla de clientes', module: 'clients', resource: 'clients', action: 'view', type: 'page' },
  { code: 'page.packs.view', name: 'Ver packs', description: 'Acceso a pantalla de packs', module: 'packs', resource: 'packs', action: 'view', type: 'page' },
  { code: 'page.agencies.view', name: 'Ver agencias', description: 'Acceso a pantalla de agencias', module: 'agencies', resource: 'agencies', action: 'view', type: 'page' },
  { code: 'page.sources.view', name: 'Ver fuentes', description: 'Acceso a pantalla de fuentes', module: 'sources', resource: 'sources', action: 'view', type: 'page' },
  { code: 'page.suppliers.view', name: 'Ver proveedores', description: 'Acceso a pantalla de proveedores', module: 'suppliers', resource: 'suppliers', action: 'view', type: 'page' },
  { code: 'page.purchases.view', name: 'Ver compras', description: 'Acceso a pantalla de compras', module: 'purchases', resource: 'purchases', action: 'view', type: 'page' },
  { code: 'page.purchase-receptions.view', name: 'Ver recepciones de compras', description: 'Acceso a pantalla de recepcion de compras', module: 'purchases', resource: 'purchase_receptions', action: 'view', type: 'page' },
  { code: 'page.payments.view', name: 'Ver pagos', description: 'Acceso a pantalla de pagos', module: 'payments', resource: 'payments', action: 'view', type: 'page' },
  { code: 'page.accounts-payable.view', name: 'Ver cuentas por pagar', description: 'Acceso a pantalla de cuentas por pagar', module: 'accounts_payable', resource: 'accounts_payable', action: 'view', type: 'page' },
  { code: 'page.recurring-purchases.view', name: 'Ver compras recurrentes', description: 'Acceso a pantalla de compras recurrentes', module: 'recurring_purchases', resource: 'recurring_purchases', action: 'view', type: 'page' },
  { code: 'page.production.view', name: 'Ver produccion', description: 'Acceso a pantalla de produccion', module: 'production', resource: 'production', action: 'view', type: 'page' },
  { code: 'page.security.view', name: 'Ver seguridad', description: 'Acceso a pantalla de seguridad', module: 'security', resource: 'security', action: 'view', type: 'page' },
  { code: 'page.notifications.view', name: 'Ver notificaciones', description: 'Acceso a pantalla de notificaciones', module: 'notifications', resource: 'notifications', action: 'view', type: 'page' },
  { code: 'users.read', name: 'Listar usuarios', description: 'Ver listado de usuarios', module: 'users', resource: 'users', action: 'read', type: 'action' },
  { code: 'users.create', name: 'Crear usuarios', description: 'Crear nuevos usuarios', module: 'users', resource: 'users', action: 'create', type: 'action' },
  { code: 'users.update', name: 'Editar usuarios', description: 'Actualizar perfil de usuarios', module: 'users', resource: 'users', action: 'update', type: 'action' },
  { code: 'users.delete', name: 'Eliminar usuarios', description: 'Desactivar usuarios', module: 'users', resource: 'users', action: 'delete', type: 'action' },
  { code: 'users.restore', name: 'Restaurar usuarios', description: 'Restaurar usuarios desactivados', module: 'users', resource: 'users', action: 'restore', type: 'action' },
  { code: 'users.assign_roles', name: 'Asignar roles', description: 'Cambiar rol de usuarios', module: 'users', resource: 'users', action: 'assign_roles', type: 'action' },
  { code: 'users.assign_permissions', name: 'Asignar permisos', description: 'Asignar permisos directos por usuario', module: 'users', resource: 'users', action: 'assign_permissions', type: 'action' },
  { code: 'users.deny_permissions', name: 'Denegar permisos', description: 'Denegar permisos directos por usuario', module: 'users', resource: 'users', action: 'deny_permissions', type: 'action' },
  { code: 'users.manage_grantable_permissions', name: 'Gestionar permisos delegables', description: 'Definir que permisos puede otorgar un usuario', module: 'users', resource: 'users', action: 'manage_grantable_permissions', type: 'action' },
  { code: 'users.view_effective_permissions', name: 'Ver permisos efectivos', description: 'Consultar permisos efectivos de usuario', module: 'users', resource: 'users', action: 'view_effective_permissions', type: 'action' },
  { code: 'roles.read', name: 'Listar roles', description: 'Ver listado de roles', module: 'roles', resource: 'roles', action: 'read', type: 'action' },
  { code: 'roles.create', name: 'Crear roles', description: 'Crear nuevos roles', module: 'roles', resource: 'roles', action: 'create', type: 'action' },
  { code: 'roles.update', name: 'Editar roles', description: 'Editar roles existentes', module: 'roles', resource: 'roles', action: 'update', type: 'action' },
  { code: 'roles.delete', name: 'Eliminar roles', description: 'Eliminar roles', module: 'roles', resource: 'roles', action: 'delete', type: 'action' },
  { code: 'roles.restore', name: 'Restaurar roles', description: 'Restaurar roles eliminados', module: 'roles', resource: 'roles', action: 'restore', type: 'action' },
  { code: 'roles.assign_permissions', name: 'Asignar permisos a rol', description: 'Asignar permisos base a un rol', module: 'roles', resource: 'roles', action: 'assign_permissions', type: 'action' },
  { code: 'permissions.read', name: 'Listar permisos', description: 'Consultar catalogo de permisos', module: 'permissions', resource: 'permissions', action: 'read', type: 'action' },
  { code: 'company.read', name: 'Consultar empresa', description: 'Consultar configuracion de empresa', module: 'company', resource: 'company', action: 'read', type: 'action' },
  { code: 'company.manage', name: 'Gestionar empresa', description: 'Crear y actualizar configuracion de empresa', module: 'company', resource: 'company', action: 'manage', type: 'action' },
  { code: 'identity.lookup', name: 'Consultar identidad', description: 'Consultar servicios de identidad (DNI/RUC)', module: 'identity', resource: 'identity', action: 'lookup', type: 'action' },
  { code: 'pdf.generate', name: 'Generar PDF', description: 'Generar y visualizar documentos PDF', module: 'pdf', resource: 'pdf', action: 'generate', type: 'action' },
  { code: 'purchases.read', name: 'Listar compras', description: 'Ver compras', module: 'purchases', resource: 'purchases', action: 'read', type: 'action' },
  { code: 'purchases.view', name: 'Ver compras', description: 'Ver listado y resumen de compras', module: 'purchases', resource: 'purchases', action: 'view', type: 'action' },
  { code: 'purchases.create', name: 'Crear compras', description: 'Crear nuevas compras', module: 'purchases', resource: 'purchases', action: 'create', type: 'action' },
  { code: 'purchases.edit', name: 'Editar compras', description: 'Editar compras', module: 'purchases', resource: 'purchases', action: 'edit', type: 'action' },
  { code: 'purchases.edit_draft', name: 'Editar borradores de compra', description: 'Editar compras en estado borrador', module: 'purchases', resource: 'purchases', action: 'edit_draft', type: 'action' },
  { code: 'purchases.cancel', name: 'Cancelar compras', description: 'Cancelar compras', module: 'purchases', resource: 'purchases', action: 'cancel', type: 'action' },
  { code: 'purchases.cancel_draft', name: 'Cancelar borradores de compra', description: 'Cancelar compras en estado borrador', module: 'purchases', resource: 'purchases', action: 'cancel_draft', type: 'action' },
  { code: 'purchases.delete', name: 'Eliminar compras', description: 'Eliminar compras', module: 'purchases', resource: 'purchases', action: 'delete', type: 'action' },
  { code: 'purchases.delete_processed_purchase', name: 'Eliminar compras procesadas', description: 'Eliminar compras ya procesadas', module: 'purchases', resource: 'purchases', action: 'delete_processed_purchase', type: 'action' },
  { code: 'purchases.process', name: 'Procesar compras', description: 'Solicitar o ejecutar procesamiento de compras', module: 'purchases', resource: 'purchases', action: 'process', type: 'action' },
  { code: 'purchases.process.request', name: 'Solicitar procesamiento de compra', description: 'Solicitar aprobacion de procesamiento', module: 'purchases', resource: 'purchases', action: 'process.request', type: 'action' },
  { code: 'purchases.view_detail', name: 'Ver detalle de compra', description: 'Ver detalle completo de una compra', module: 'purchases', resource: 'purchases', action: 'view_detail', type: 'action' },
  { code: 'purchases.view_payments', name: 'Ver pagos de compras', description: 'Ver pagos asociados a compras', module: 'purchases', resource: 'purchases', action: 'view_payments', type: 'action' },
  { code: 'purchases.create_payment', name: 'Registrar pagos de compras', description: 'Registrar pagos asociados a compras', module: 'purchases', resource: 'purchases', action: 'create_payment', type: 'action' },
  { code: 'purchases.attachments.view', name: 'Ver documentos de compras', description: 'Ver documentos y evidencias adjuntas a compras', module: 'purchases', resource: 'attachments', action: 'view', type: 'action' },
  { code: 'purchases.attachments.upload', name: 'Subir documentos de compras', description: 'Subir documentos y evidencias adjuntas a compras', module: 'purchases', resource: 'attachments', action: 'upload', type: 'action' },
  { code: 'purchases.attachments.delete', name: 'Eliminar documentos de compras', description: 'Eliminar documentos y evidencias adjuntas a compras', module: 'purchases', resource: 'attachments', action: 'delete', type: 'action' },
  { code: 'purchases.upload_photo', name: 'Subir foto de compra', description: 'Subir foto de evidencia de compra', module: 'purchases', resource: 'purchases', action: 'upload_photo', type: 'action' },
  { code: 'purchases.upload_processed_photo', name: 'Subir foto de compra procesada', description: 'Subir foto de compras procesadas', module: 'purchases', resource: 'purchases', action: 'upload_processed_photo', type: 'action' },
  { code: 'purchases.view_history', name: 'Ver historial de compras', description: 'Ver historial y auditoria de compras', module: 'purchases', resource: 'purchases', action: 'view_history', type: 'action' },
  { code: 'purchases.approve_creation_with_payment', name: 'Aprobar creación de compra con pago', description: 'Aprobar compras creadas con pago directo', module: 'purchases', resource: 'purchases', action: 'approve_creation_with_payment', type: 'action' },
  { code: 'purchases.approve_payment', name: 'Aprobar pago de compra', description: 'Aprobar o rechazar pagos de compras', module: 'purchases', resource: 'purchases', action: 'approve_payment', type: 'action' },
  { code: 'purchases.approve_processing', name: 'Aprobar procesamiento de compra', description: 'Aprobar o rechazar procesamiento de compras', module: 'purchases', resource: 'purchases', action: 'approve_processing', type: 'action' },
  { code: 'purchases.approve', name: 'Aprobar compra', description: 'Aprobar procesamiento de compra', module: 'purchases', resource: 'purchases', action: 'approve', type: 'action' },
  { code: 'purchases.reject', name: 'Rechazar compra', description: 'Rechazar solicitudes o procesamiento de compras', module: 'purchases', resource: 'purchases', action: 'reject', type: 'action' },
  { code: 'purchases.submit', name: 'Enviar compra', description: 'Enviar compras para procesamiento o aprobacion', module: 'purchases', resource: 'purchases', action: 'submit', type: 'action' },
  { code: 'purchases.receive', name: 'Registrar recepcion de compra', description: 'Registrar y confirmar recepciones de compras', module: 'purchases', resource: 'purchase_receptions', action: 'receive', type: 'action' },
  { code: 'purchases.receive_stock', name: 'Recibir stock de compra', description: 'Confirmar recepciones que impactan inventario', module: 'purchases', resource: 'purchase_receptions', action: 'receive_stock', type: 'action' },
  { code: 'purchases.manage_internal_material', name: 'Gestionar material interno', description: 'Gestionar compras de material interno sin venta directa', module: 'purchases', resource: 'purchases', action: 'manage_internal_material', type: 'action' },
  { code: 'purchases.manage_assets', name: 'Gestionar activos', description: 'Gestionar compras de activos y equipos', module: 'purchases', resource: 'purchases', action: 'manage_assets', type: 'action' },
  { code: 'purchases.manage_services', name: 'Gestionar servicios', description: 'Gestionar compras de servicios, membresias y suscripciones', module: 'purchases', resource: 'purchases', action: 'manage_services', type: 'action' },
  { code: 'purchases.export', name: 'Exportar compras', description: 'Exportar compras e historial a archivos', module: 'purchases', resource: 'purchases', action: 'export', type: 'action' },
  { code: 'purchases.view_costs', name: 'Ver costos de compras', description: 'Ver costos, importes y totales de compras', module: 'purchases', resource: 'purchases', action: 'view_costs', type: 'action' },
  { code: 'purchases.attach_documents', name: 'Adjuntar documentos de compras', description: 'Adjuntar documentos y evidencias a compras', module: 'purchases', resource: 'purchase_documents', action: 'attach_documents', type: 'action' },
  { code: 'purchases.delete_documents', name: 'Eliminar documentos de compras', description: 'Eliminar documentos y evidencias de compras', module: 'purchases', resource: 'purchase_documents', action: 'delete_documents', type: 'action' },
  { code: 'purchases.view_all', name: 'Ver todas las compras', description: 'Permite ver todas las compras del sistema', module: 'purchases', resource: 'purchases', action: 'view_all', type: 'action' },
  { code: 'purchases.view_created_by_others', name: 'Ver compras de otros usuarios', description: 'Permite ver compras creadas por otros usuarios', module: 'purchases', resource: 'purchases', action: 'view_created_by_others', type: 'action' },
  { code: 'purchases.view_creator_info', name: 'Ver creador de compra', description: 'Permite ver qué usuario creó una compra', module: 'purchases', resource: 'purchases', action: 'view_creator_info', type: 'action' },
  { code: 'purchases.receive_created_purchase_notifications', name: 'Recibir notificaciones de compras creadas', description: 'Recibir notificaciones cuando otros usuarios crean compras', module: 'purchases', resource: 'purchases', action: 'receive_created_purchase_notifications', type: 'action' },
  { code: 'notifications.read', name: 'Listar notificaciones', description: 'Consultar notificaciones', module: 'notifications', resource: 'notifications', action: 'read', type: 'action' },
  { code: 'notifications.manage', name: 'Gestionar notificaciones', description: 'Marcar, archivar y gestionar notificaciones propias', module: 'notifications', resource: 'notifications', action: 'manage', type: 'action' },
  { code: 'notifications.labels.create', name: 'Crear etiquetas de correo', description: 'Permite crear etiquetas personalizadas de correo', module: 'notifications', resource: 'notifications', action: 'labels.create', type: 'action' },
  { code: 'catalog.read', name: 'Consultar catalogo', description: 'Consultar productos, stock, documentos y consultas de catalogo', module: 'catalog', resource: 'catalog', action: 'read', type: 'action' },
  { code: 'catalog.manage', name: 'Gestionar catalogo', description: 'Crear, editar y operar recursos del catalogo', module: 'catalog', resource: 'catalog', action: 'manage', type: 'action' },
  { code: 'catalog.export', name: 'Exportar catalogo', description: 'Exportar reportes del catalogo e inventario', module: 'catalog', resource: 'catalog', action: 'export', type: 'action' },
  { code: 'warehouses.read', name: 'Consultar almacenes', description: 'Consultar almacenes y ubicaciones', module: 'warehouses', resource: 'warehouses', action: 'read', type: 'action' },
  { code: 'warehouses.create', name: 'Crear almacenes', description: 'Crear almacenes', module: 'warehouses', resource: 'warehouses', action: 'create', type: 'action' },
  { code: 'warehouses.update', name: 'Editar almacenes', description: 'Editar almacenes', module: 'warehouses', resource: 'warehouses', action: 'update', type: 'action' },
  { code: 'warehouses.delete', name: 'Desactivar almacenes', description: 'Desactivar o restaurar almacenes', module: 'warehouses', resource: 'warehouses', action: 'delete', type: 'action' },
  { code: 'warehouses.locations.manage', name: 'Gestionar ubicaciones de almacen', description: 'Crear, editar y desactivar ubicaciones de almacenes', module: 'warehouses', resource: 'warehouse_locations', action: 'manage', type: 'action' },
  { code: 'warehouses.manage', name: 'Gestionar almacenes', description: 'Permiso legacy para crear, editar y activar almacenes', module: 'warehouses', resource: 'warehouses', action: 'manage', type: 'action' },
  { code: 'clients.read', name: 'Consultar clientes', description: 'Consultar clientes y telefonos', module: 'clients', resource: 'clients', action: 'read', type: 'action' },
  { code: 'clients.manage', name: 'Gestionar clientes', description: 'Crear, editar y activar clientes y telefonos', module: 'clients', resource: 'clients', action: 'manage', type: 'action' },
  { code: 'packs.read', name: 'Consultar packs', description: 'Consultar packs y sus items', module: 'packs', resource: 'packs', action: 'read', type: 'action' },
  { code: 'packs.manage', name: 'Gestionar packs', description: 'Crear, editar y activar/desactivar packs', module: 'packs', resource: 'packs', action: 'manage', type: 'action' },
  ...CATALOG_FINE_ACTION_PERMISSIONS,
  { code: 'suppliers.read', name: 'Consultar proveedores', description: 'Consultar proveedores y codigos de proveedor por SKU', module: 'suppliers', resource: 'suppliers', action: 'read', type: 'action' },
  { code: 'suppliers.create', name: 'Crear proveedores', description: 'Crear proveedores', module: 'suppliers', resource: 'suppliers', action: 'create', type: 'action' },
  { code: 'suppliers.update', name: 'Editar proveedores', description: 'Editar proveedores', module: 'suppliers', resource: 'suppliers', action: 'update', type: 'action' },
  { code: 'suppliers.delete', name: 'Desactivar proveedores', description: 'Desactivar o reactivar proveedores', module: 'suppliers', resource: 'suppliers', action: 'delete', type: 'action' },
  { code: 'suppliers.payment_methods.manage', name: 'Gestionar metodos de pago de proveedor', description: 'Agregar, editar o quitar metodos de pago asignados a proveedores', module: 'suppliers', resource: 'supplier_payment_methods', action: 'manage', type: 'action' },
  { code: 'suppliers.manage', name: 'Gestionar proveedores', description: 'Permiso legacy para crear, editar y activar proveedores y codigos por SKU', module: 'suppliers', resource: 'suppliers', action: 'manage', type: 'action' },
  { code: 'payments.read', name: 'Consultar pagos', description: 'Consultar pagos y cuotas de credito', module: 'payments', resource: 'payments', action: 'read', type: 'action' },
  { code: 'payments.manage', name: 'Gestionar pagos', description: 'Crear y eliminar pagos y cuotas de credito', module: 'payments', resource: 'payments', action: 'manage', type: 'action' },
  { code: 'payments.create', name: 'Crear pagos', description: 'Registrar pagos manuales o asociados a compras', module: 'payments', resource: 'payments', action: 'create', type: 'action' },
  { code: 'payments.schedule', name: 'Programar pagos', description: 'Programar pagos futuros y vencimientos', module: 'payments', resource: 'payments', action: 'schedule', type: 'action' },
  { code: 'payments.approve', name: 'Aprobar pagos', description: 'Aprobar pagos pendientes o programados', module: 'payments', resource: 'payments', action: 'approve', type: 'action' },
  { code: 'payments.reject', name: 'Rechazar pagos', description: 'Rechazar pagos pendientes de aprobacion', module: 'payments', resource: 'payments', action: 'reject', type: 'action' },
  { code: 'payments.delete', name: 'Eliminar pagos', description: 'Eliminar pagos registrados cuando corresponda', module: 'payments', resource: 'payments', action: 'delete', type: 'action' },
  { code: 'payments.attach_evidence', name: 'Adjuntar evidencia de pago', description: 'Adjuntar comprobantes y evidencias a pagos', module: 'payments', resource: 'payment_evidence', action: 'attach_evidence', type: 'action' },
  { code: 'payments.view_evidence', name: 'Ver evidencia de pago', description: 'Ver comprobantes y evidencias de pagos', module: 'payments', resource: 'payment_evidence', action: 'view_evidence', type: 'action' },
  { code: 'payments.view_all', name: 'Ver todos los pagos', description: 'Consultar pagos de todos los usuarios', module: 'payments', resource: 'payments', action: 'view_all', type: 'action' },
  { code: 'payments.view_own', name: 'Ver pagos propios', description: 'Consultar pagos propios o solicitados por el usuario', module: 'payments', resource: 'payments', action: 'view_own', type: 'action' },
  { code: 'payments.export', name: 'Exportar pagos', description: 'Exportar reportes de pagos', module: 'payments', resource: 'payments', action: 'export', type: 'action' },
  { code: 'accounts-payable.view', name: 'Consultar cuentas por pagar', description: 'Consultar cuentas por pagar y sus saldos', module: 'accounts_payable', resource: 'accounts_payable', action: 'view', type: 'action' },
  { code: 'accounts-payable.manage', name: 'Gestionar cuentas por pagar', description: 'Registrar pagos asociados a cuentas por pagar', module: 'accounts_payable', resource: 'accounts_payable', action: 'manage', type: 'action' },
  { code: 'accounts-payable.mark_overdue', name: 'Marcar cuentas vencidas', description: 'Actualizar cuentas por pagar vencidas', module: 'accounts_payable', resource: 'accounts_payable', action: 'mark_overdue', type: 'action' },
  { code: 'page.payment-accounts.view', name: 'Ver cuentas de pago', description: 'Acceso a pantalla de cuentas/tarjetas de pago de empresa', module: 'payment_accounts', resource: 'payment_accounts', action: 'view', type: 'page' },
  { code: 'payment_accounts.view', name: 'Consultar cuentas de pago', description: 'Consultar cuentas/tarjetas/cajas de pago de empresa', module: 'payment_accounts', resource: 'payment_accounts', action: 'view', type: 'action' },
  { code: 'payment_accounts.create', name: 'Crear cuentas de pago', description: 'Crear cuentas/tarjetas/cajas de pago de empresa', module: 'payment_accounts', resource: 'payment_accounts', action: 'create', type: 'action' },
  { code: 'payment_accounts.edit', name: 'Editar cuentas de pago', description: 'Editar cuentas/tarjetas/cajas de pago de empresa', module: 'payment_accounts', resource: 'payment_accounts', action: 'edit', type: 'action' },
  { code: 'payment_accounts.disable', name: 'Desactivar cuentas de pago', description: 'Activar o desactivar cuentas/tarjetas/cajas de pago de empresa', module: 'payment_accounts', resource: 'payment_accounts', action: 'disable', type: 'action' },
  { code: 'payment_accounts.delete', name: 'Eliminar cuentas de pago', description: 'Eliminar cuentas/tarjetas/cajas de pago de empresa cuando no tengan uso', module: 'payment_accounts', resource: 'payment_accounts', action: 'delete', type: 'action' },
  { code: 'payment_accounts.view_sensitive', name: 'Ver datos sensibles de cuentas', description: 'Ver datos sensibles no enmascarados de cuentas de pago', module: 'payment_accounts', resource: 'payment_accounts', action: 'view_sensitive', type: 'action' },
  { code: 'recurring_purchases.view', name: 'Consultar compras recurrentes', description: 'Consultar plantillas de compras recurrentes', module: 'recurring_purchases', resource: 'recurring_purchases', action: 'view', type: 'action' },
  { code: 'recurring_purchases.create', name: 'Crear compras recurrentes', description: 'Crear plantillas de compras recurrentes', module: 'recurring_purchases', resource: 'recurring_purchases', action: 'create', type: 'action' },
  { code: 'recurring_purchases.edit', name: 'Editar compras recurrentes', description: 'Editar plantillas de compras recurrentes', module: 'recurring_purchases', resource: 'recurring_purchases', action: 'edit', type: 'action' },
  { code: 'recurring_purchases.pause', name: 'Pausar compras recurrentes', description: 'Pausar o reanudar compras recurrentes', module: 'recurring_purchases', resource: 'recurring_purchases', action: 'pause', type: 'action' },
  { code: 'recurring_purchases.cancel', name: 'Cancelar compras recurrentes', description: 'Cancelar compras recurrentes', module: 'recurring_purchases', resource: 'recurring_purchases', action: 'cancel', type: 'action' },
  { code: 'recurring_purchases.pay', name: 'Generar cuenta por pagar recurrente', description: 'Generar cuenta por pagar del periodo recurrente', module: 'recurring_purchases', resource: 'recurring_purchases', action: 'pay', type: 'action' },
  { code: 'purchases_dashboard.view', name: 'Ver dashboard de compras', description: 'Consultar metricas y graficos de compras', module: 'purchases_dashboard', resource: 'purchases_dashboard', action: 'view', type: 'action' },
  { code: 'purchases_dashboard.view_costs', name: 'Ver costos en dashboard de compras', description: 'Ver importes y costos agregados en dashboard de compras', module: 'purchases_dashboard', resource: 'purchases_dashboard', action: 'view_costs', type: 'action' },
  { code: 'purchases_dashboard.export', name: 'Exportar dashboard de compras', description: 'Exportar datos del dashboard de compras', module: 'purchases_dashboard', resource: 'purchases_dashboard', action: 'export', type: 'action' },
  { code: 'payment-methods.read', name: 'Consultar metodos de pago', description: 'Consultar metodos de pago y asignaciones', module: 'payment_methods', resource: 'payment_methods', action: 'read', type: 'action' },
  { code: 'payment-methods.manage', name: 'Gestionar metodos de pago', description: 'Crear, editar, activar y eliminar metodos de pago y asignaciones', module: 'payment_methods', resource: 'payment_methods', action: 'manage', type: 'action' },
  { code: 'production.read', name: 'Listar produccion', description: 'Consultar ordenes de produccion', module: 'production', resource: 'production', action: 'read', type: 'action' },
  { code: 'production.create', name: 'Crear orden de produccion', description: 'Crear nuevas ordenes de produccion', module: 'production', resource: 'production', action: 'create', type: 'action' },
  { code: 'production.update', name: 'Editar orden de produccion', description: 'Actualizar datos de orden de produccion', module: 'production', resource: 'production', action: 'update', type: 'action' },
  { code: 'production.start', name: 'Iniciar orden de produccion', description: 'Iniciar una orden de produccion', module: 'production', resource: 'production', action: 'start', type: 'action' },
  { code: 'production.close', name: 'Cerrar orden de produccion', description: 'Cerrar una orden de produccion', module: 'production', resource: 'production', action: 'close', type: 'action' },
  { code: 'production.cancel', name: 'Cancelar orden de produccion', description: 'Cancelar una orden de produccion', module: 'production', resource: 'production', action: 'cancel', type: 'action' },
  { code: 'production.extra-time', name: 'Agregar tiempo extra', description: 'Agregar tiempo extra a una orden de produccion', module: 'production', resource: 'production', action: 'extra-time', type: 'action' },
  { code: 'production.image.upload', name: 'Subir imagen de produccion', description: 'Subir evidencia fotografica de produccion', module: 'production', resource: 'production', action: 'image.upload', type: 'action' },
  { code: 'production.export', name: 'Exportar produccion', description: 'Exportar reportes de produccion', module: 'production', resource: 'production', action: 'export', type: 'action' },
  ...PRODUCTION_FINE_ACTION_PERMISSIONS,
  { code: 'security.read', name: 'Consultar seguridad', description: 'Consultar metricas y reportes de seguridad', module: 'security', resource: 'security', action: 'read', type: 'action' },
  { code: 'agencies.read', name: 'Consultar agencias', description: 'Consultar agencias', module: 'agencies', resource: 'agencies', action: 'read', type: 'action' },
  { code: 'agencies.manage', name: 'Gestionar agencias', description: 'Crear/actualizar agencias y su estado', module: 'agencies', resource: 'agencies', action: 'manage', type: 'action' },
  { code: 'sources.read', name: 'Consultar fuentes', description: 'Consultar fuentes', module: 'sources', resource: 'sources', action: 'read', type: 'action' },
  { code: 'sources.manage', name: 'Gestionar fuentes', description: 'Crear/actualizar fuentes y su estado', module: 'sources', resource: 'sources', action: 'manage', type: 'action' },
  { code: 'bank-accounts.read', name: 'Consultar cuentas bancarias', description: 'Consultar cuentas bancarias por empresa', module: 'bank_accounts', resource: 'bank_accounts', action: 'read', type: 'action' },
  { code: 'bank-accounts.manage', name: 'Gestionar cuentas bancarias', description: 'Crear/actualizar cuentas bancarias y su estado', module: 'bank_accounts', resource: 'bank_accounts', action: 'manage', type: 'action' },
];


