export type SaleOrderPermissionSeed = {
  code: string;
  name: string;
  description: string;
  module: "sale_orders";
  resource: string;
  action: string;
  type: "action" | "page";
};

export const SALE_ORDER_PERMISSIONS: ReadonlyArray<Readonly<SaleOrderPermissionSeed>> = [
  {
    code: "page.sale-orders.view",
    name: "Ingresar a Pedidos",
    description: "Mostrar el menu y abrir la pagina de pedidos",
    module: "sale_orders",
    resource: "sale_orders",
    action: "view",
    type: "page",
  },
  {
    code: "sale_orders.view",
    name: "Ver pedidos propios o asignados",
    description: "Listar y buscar pedidos creados por el usuario o asignados a el",
    module: "sale_orders",
    resource: "sale_orders",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.view_all",
    name: "Ver todos los pedidos",
    description: "Ampliar el alcance a pedidos de cualquier usuario",
    module: "sale_orders",
    resource: "sale_orders",
    action: "view_all",
    type: "action",
  },
  {
    code: "sale_orders.view_detail",
    name: "Ver detalle de pedido",
    description: "Abrir el detalle de un pedido visible en modo de solo lectura",
    module: "sale_orders",
    resource: "sale_orders",
    action: "view_detail",
    type: "action",
  },
  {
    code: "sale_orders.view_deleted",
    name: "Ver pedidos eliminados",
    description: "Consultar pedidos archivados con isActive=false",
    module: "sale_orders",
    resource: "sale_orders",
    action: "view_deleted",
    type: "action",
  },
  {
    code: "sale_orders.view_statistics",
    name: "Ver estadisticas de pedidos",
    description: "Consultar agregados de pedidos respetando el alcance del usuario",
    module: "sale_orders",
    resource: "sale_order_statistics",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.view_customer_data",
    name: "Ver datos del cliente en pedidos",
    description: "Mostrar documento, telefonos y direccion del cliente",
    module: "sale_orders",
    resource: "sale_order_customer",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.view_amounts",
    name: "Ver importes de pedidos",
    description: "Mostrar precios, costos, totales, pagos y saldos",
    module: "sale_orders",
    resource: "sale_order_amounts",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.products.view",
    name: "Ver productos en pedidos",
    description: "Consultar productos terminados desde el contexto de pedidos",
    module: "sale_orders",
    resource: "sale_order_products",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.stock.view",
    name: "Ver stock en pedidos",
    description: "Consultar disponibilidad de productos terminados del pedido",
    module: "sale_orders",
    resource: "sale_order_stock",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.create",
    name: "Crear pedido nuevo",
    description: "Crear pedidos nuevos",
    module: "sale_orders",
    resource: "sale_orders",
    action: "create",
    type: "action",
  },
  {
    code: "sale_orders.update",
    name: "Modificar pedido",
    description: "Editar los campos generales de un pedido visible",
    module: "sale_orders",
    resource: "sale_orders",
    action: "update",
    type: "action",
  },
  {
    code: "sale_orders.delete",
    name: "Eliminar pedido",
    description: "Archivar uno o varios pedidos de forma logica",
    module: "sale_orders",
    resource: "sale_orders",
    action: "delete",
    type: "action",
  },
  {
    code: "sale_orders.restore",
    name: "Restaurar pedido",
    description: "Reactivar uno o varios pedidos archivados",
    module: "sale_orders",
    resource: "sale_orders",
    action: "restore",
    type: "action",
  },
  {
    code: "sale_orders.clients.manage",
    name: "Gestionar cliente desde pedido",
    description: "Seleccionar, crear o actualizar clientes desde el editor de pedidos",
    module: "sale_orders",
    resource: "sale_order_clients",
    action: "manage",
    type: "action",
  },
  {
    code: "sale_orders.assign_adviser",
    name: "Asignar asesor",
    description: "Asignar o quitar asesor individual o masivamente",
    module: "sale_orders",
    resource: "sale_orders",
    action: "assign_adviser",
    type: "action",
  },
  {
    code: "sale_orders.assign_workflow",
    name: "Asignar tipo de pedido",
    description: "Asignar o cambiar el flujo de un pedido",
    module: "sale_orders",
    resource: "sale_orders",
    action: "assign_workflow",
    type: "action",
  },
  {
    code: "sale_orders.change_state",
    name: "Cambiar estado",
    description: "Ejecutar transiciones de estado individuales o masivas",
    module: "sale_orders",
    resource: "sale_orders",
    action: "change_state",
    type: "action",
  },
  {
    code: "sale_orders.execute_workflow_action",
    name: "Ejecutar accion global del flujo",
    description: "Ejecutar acciones globales de workflow sobre pedidos activos",
    module: "sale_orders",
    resource: "sale_orders",
    action: "execute_workflow_action",
    type: "action",
  },
  {
    code: "sale_orders.preguide.update",
    name: "Cambiar estado de preguia",
    description: "Marcar o desmarcar preguia individual o masivamente",
    module: "sale_orders",
    resource: "sale_order_tracking",
    action: "update",
    type: "action",
  },
  {
    code: "sale_orders.prepared.update",
    name: "Cambiar estado de preparacion",
    description: "Marcar o desmarcar preparacion individual o masivamente",
    module: "sale_orders",
    resource: "sale_order_tracking",
    action: "update",
    type: "action",
  },
  {
    code: "sale_orders.cancel",
    name: "Cancelar pedido",
    description: "Ejecutar la cancelacion formal de un pedido",
    module: "sale_orders",
    resource: "sale_orders",
    action: "cancel",
    type: "action",
  },
  {
    code: "sale_orders.confirm_delivery",
    name: "Confirmar entrega",
    description: "Confirmar la entrega de un pedido",
    module: "sale_orders",
    resource: "sale_orders",
    action: "confirm_delivery",
    type: "action",
  },
  {
    code: "sale_orders.view_history",
    name: "Ver historial del flujo",
    description: "Consultar la linea de tiempo de estados y transiciones",
    module: "sale_orders",
    resource: "sale_order_history",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.view_audit",
    name: "Ver auditoria del pedido",
    description: "Consultar cambios, actor y fecha del pedido",
    module: "sale_orders",
    resource: "sale_order_audit",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.payments.view",
    name: "Ver pagos del pedido",
    description: "Ver pagos, cuentas, comprobantes y detalle financiero del pedido",
    module: "sale_orders",
    resource: "sale_order_payments",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.payments.create",
    name: "Registrar pago en pedido",
    description: "Agregar pagos desde el pedido",
    module: "sale_orders",
    resource: "sale_order_payments",
    action: "create",
    type: "action",
  },
  {
    code: "sale_orders.payments.update",
    name: "Modificar pago de pedido",
    description: "Cambiar datos de pagos existentes del pedido",
    module: "sale_orders",
    resource: "sale_order_payments",
    action: "update",
    type: "action",
  },
  {
    code: "sale_orders.payments.delete",
    name: "Eliminar pago de pedido",
    description: "Eliminar pagos del pedido",
    module: "sale_orders",
    resource: "sale_order_payments",
    action: "delete",
    type: "action",
  },
  {
    code: "sale_orders.attachments.view",
    name: "Ver adjuntos del pedido",
    description: "Listar y visualizar fotos y comprobantes del pedido",
    module: "sale_orders",
    resource: "sale_order_attachments",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.attachments.upload",
    name: "Subir adjuntos del pedido",
    description: "Adjuntar fotos y comprobantes al pedido",
    module: "sale_orders",
    resource: "sale_order_attachments",
    action: "upload",
    type: "action",
  },
  {
    code: "sale_orders.attachments.delete",
    name: "Eliminar adjuntos del pedido",
    description: "Retirar archivos del pedido",
    module: "sale_orders",
    resource: "sale_order_attachments",
    action: "delete",
    type: "action",
  },
  {
    code: "sale_orders.import",
    name: "Importar pedidos",
    description: "Previsualizar y crear pedidos desde archivos",
    module: "sale_orders",
    resource: "sale_order_import",
    action: "import",
    type: "action",
  },
  {
    code: "sale_orders.import_lotes.view",
    name: "Ver lotes importados",
    description: "Listar lotes importados y consultar su auditoria",
    module: "sale_orders",
    resource: "sale_order_import_lotes",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.import_lotes.manage",
    name: "Gestionar lotes importados",
    description: "Eliminar o restaurar lotes importados y sus pedidos",
    module: "sale_orders",
    resource: "sale_order_import_lotes",
    action: "manage",
    type: "action",
  },
  {
    code: "sale_orders.export",
    name: "Exportar pedidos",
    description: "Configurar y descargar exportaciones de pedidos",
    module: "sale_orders",
    resource: "sale_orders",
    action: "export",
    type: "action",
  },
  {
    code: "sale_orders.pdf.view",
    name: "Ver PDF de pedido",
    description: "Generar y abrir el documento PDF del pedido visible",
    module: "sale_orders",
    resource: "sale_order_pdf",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.workflows.view",
    name: "Consultar flujos y estados",
    description: "Cargar flujos y estados necesarios en Pedidos",
    module: "sale_orders",
    resource: "sale_order_workflows",
    action: "view",
    type: "action",
  },
  {
    code: "sale_orders.workflows.manage",
    name: "Diseñar flujos y estados",
    description: "Crear y editar flujos, estados, transiciones y acciones",
    module: "sale_orders",
    resource: "sale_order_workflows",
    action: "manage",
    type: "action",
  },
];

export const SALE_ORDER_PERMISSION_CODES: ReadonlyArray<string> = SALE_ORDER_PERMISSIONS.map(({ code }) => code);
