export const ACTIONS = {
  RESERVE_STOCK: "RESERVE_STOCK",
  CONSUME_STOCK: "CONSUME_STOCK",
  REVERT_STOCK: "REVERT_STOCK",
  MARK_INVOICE_SENT: "MARK_INVOICE_SENT",
  MARK_PREGUIDE: "MARK_PREGUIDE",
  MARK_PREPARED: "MARK_PREPARED",
  ASSIGN_WAREHOUSE_BY_PROVINCE: "ASSIGN_WAREHOUSE_BY_PROVINCE",
  ASSIGN_WAREHOUSE_BY_WORKFLOW: "ASSIGN_WAREHOUSE_BY_WORKFLOW",
} as const;

export type WorkflowActionType = typeof ACTIONS[keyof typeof ACTIONS];
