export const PURCHASE_NOTIFICATION_TYPES = {
  PURCHASE_CREATED: "PURCHASE_CREATED",
  PURCHASE_SENT: "PURCHASE_SENT",
  PURCHASE_PENDING_STOCK_CONFIRMATION: "PURCHASE_PENDING_STOCK_CONFIRMATION",
  PURCHASE_PHOTO_UPLOADED: "PURCHASE_PHOTO_UPLOADED",
  PURCHASE_PHOTO_SKIPPED: "PURCHASE_PHOTO_SKIPPED",
  PURCHASE_STOCK_POSTED: "PURCHASE_STOCK_POSTED",
  PURCHASE_CANCELLED: "PURCHASE_CANCELLED",
  PURCHASE_PAYMENT_CREATED: "PURCHASE_PAYMENT_CREATED",
  PURCHASE_QUOTA_CREATED: "PURCHASE_QUOTA_CREATED",
  PURCHASE_QUOTA_PAID: "PURCHASE_QUOTA_PAID",
  PURCHASE_UPDATED: "PURCHASE_UPDATED",
  PURCHASE_PROCESSING_REQUESTED: "PURCHASE_PROCESSING_REQUESTED",
  PURCHASE_PROCESSING_APPROVED: "PURCHASE_PROCESSING_APPROVED",
  PURCHASE_PROCESSING_REJECTED: "PURCHASE_PROCESSING_REJECTED",
  PURCHASE_CREATION_WITH_PAYMENT_PENDING: "PURCHASE_CREATION_WITH_PAYMENT_PENDING",
  PURCHASE_CREATION_WITH_PAYMENT_APPROVED: "PURCHASE_CREATION_WITH_PAYMENT_APPROVED",
  PURCHASE_CREATION_WITH_PAYMENT_REJECTED: "PURCHASE_CREATION_WITH_PAYMENT_REJECTED",
  PURCHASE_PAYMENT_PENDING_APPROVAL: "PURCHASE_PAYMENT_PENDING_APPROVAL",
  PURCHASE_PAYMENT_APPROVED: "PURCHASE_PAYMENT_APPROVED",
  PURCHASE_PAYMENT_REJECTED: "PURCHASE_PAYMENT_REJECTED",
} as const;

export type PurchaseNotificationType =
  typeof PURCHASE_NOTIFICATION_TYPES[keyof typeof PURCHASE_NOTIFICATION_TYPES];

