export const PURCHASE_NOTIFICATION_TYPES = {
  PURCHASE_CREATED: "PURCHASE_CREATED",
  PURCHASE_SENT: "PURCHASE_SENT",
  PURCHASE_PENDING_STOCK_CONFIRMATION: "PURCHASE_PENDING_STOCK_CONFIRMATION",
  PURCHASE_PHOTO_UPLOADED: "PURCHASE_PHOTO_UPLOADED",
  PURCHASE_PHOTO_SKIPPED: "PURCHASE_PHOTO_SKIPPED",
  PURCHASE_STOCK_POSTED: "PURCHASE_STOCK_POSTED",
  PURCHASE_CANCELLED: "PURCHASE_CANCELLED",
  PURCHASE_PAYMENT_CREATED: "PURCHASE_PAYMENT_CREATED",
  PURCHASE_QUOTA_CREATED: "PURCHASE_QUOTA_CREATED",
  PURCHASE_QUOTA_PAID: "PURCHASE_QUOTA_PAID",
  PURCHASE_UPDATED: "PURCHASE_UPDATED",
} as const;

export type PurchaseNotificationType =
  typeof PURCHASE_NOTIFICATION_TYPES[keyof typeof PURCHASE_NOTIFICATION_TYPES];

