export enum PurchaseOrderStatus {
  DRAFT = "DRAFT",
  SENT = "SENT",
  PARTIAL = "PARTIAL",
  PENDING_RECEIPT_CONFIRMATION = "PENDING_RECEIPT_CONFIRMATION",
  RECEIVED = "RECEIVED",
  CANCELLED = "CANCELLED",
}
