export enum PurchaseItemType {
  PRODUCT = "PRODUCT",
  RAW_MATERIAL = "RAW_MATERIAL",
  SUPPLY = "SUPPLY",
  INTERNAL_MATERIAL = "INTERNAL_MATERIAL",
  FIXED_ASSET = "FIXED_ASSET",
  SERVICE = "SERVICE",
  SUBSCRIPTION = "SUBSCRIPTION",
}
