export enum PurchaseType {
  INVENTORY = "INVENTORY",
  RAW_MATERIAL = "RAW_MATERIAL",
  INTERNAL_MATERIAL = "INTERNAL_MATERIAL",
  FIXED_ASSET = "FIXED_ASSET",
  SERVICE = "SERVICE",
  SUBSCRIPTION = "SUBSCRIPTION",
  MIXED = "MIXED",
}
